<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-LFB9P6R" failures="1" tests="3" name="chromeTest" time="33.134" errors="0" timestamp="2023-06-05T12:42:55 PDT">
  <testcase classname="com.automation.tests.AutomationScripts" name="Student_registration_Form" time="7.628"/>
  <testcase classname="com.automation.tests.AutomationScripts" name="error_login_firebase_testscript" time="7.586">
    <failure type="java.lang.AssertionError" message="expected [Error : There is no user record corresponding to this identifier. The user may have been deleted.] but found [Error : There is no user record corresponding to this identifier. The user may have been deleted.dd]">
      <![CDATA[java.lang.AssertionError: expected [Error : There is no user record corresponding to this identifier. The user may have been deleted.] but found [Error : There is no user record corresponding to this identifier. The user may have been deleted.dd]
at com.automation.tests.AutomationScripts.error_login_firebase_testscript(AutomationScripts.java:91)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- error_login_firebase_testscript -->
  <testcase classname="com.automation.tests.AutomationScripts" name="login_to_firebase_testscript" time="2.616"/>
</testsuite> <!-- chromeTest -->
